GSLUX-670: Fix drag and drop for firefox
Geoportail-Luxembourg/luxembourg-geoportail pull request #96
Opened 2024-04-22 14:12 UTC by AlitaBernachot

### JIRA issue

https://jira.camptocamp.com/browse/GSLUX-XXX

### Description

- Fixed drag and drop on firefox (force Sortablejs to enable dragndrop fallback -no html5 dnd-)
- Fixed ghost dragging style for firefox
- Added `--force` option to force vite to clean node_modules cache on `npm start` (dev mode only)

2024-04-24 09:42 UTC, mki-c2c requested changes
Integration in v3 does not seem to work correctly:
while dragging, all layers become invisible and items can only be dragged upwards, not downwards.

2024-04-25 10:01 UTC, mki-c2c approved these changes
could you please rename the typos ?

2024-04-25 10:47 UTC, AlitaBernachot commented on src/components/layer-manager/layer-item/layer-item.spec.ts
> +        dragHandlerClassName: 'classnamedragg',
yes, good point

2024-04-25 10:48 UTC, AlitaBernachot commented
> could you please rename the typos ?

yes, done 🙂

2024-04-25 10:55 UTC, merged